# Generated by Django 5.1 on 2025-01-06 06:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(help_text='Unit ID must be exactly 14 characters long.', max_length=14, validators=[django.core.validators.MinLengthValidator(14)])),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_address', models.TextField()),
                ('dak_id', models.CharField(blank=True, max_length=100, null=True)),
                ('codehead', models.CharField(max_length=100)),
                ('ifa_cfa', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_allotment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_expended', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_allotment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expenditure_account', models.CharField(blank=True, max_length=100, null=True)),
                ('incurred_by', models.CharField(max_length=100)),
                ('during_month', models.CharField(max_length=100)),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
                ('sanction_no', models.CharField(max_length=100)),
                ('sanction_date', models.DateField()),
                ('sanction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supply_order_no', models.CharField(max_length=100)),
                ('supply_order_date', models.DateField()),
                ('supply_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_no', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('disallowed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crv_esic_epfo_no', models.CharField(max_length=100)),
                ('crv_esic_epfo_date', models.DateField()),
                ('vendor_name', models.CharField(max_length=100)),
                ('msme_nonmsme', models.CharField(blank=True, choices=[('msme', 'MSME'), ('non-msme', 'Non-MSME')], max_length=20, null=True)),
                ('vendor_bank_account', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=11)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('paying_authority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('item_description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_type', models.CharField(max_length=50)),
                ('tax_type', models.CharField(max_length=50)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='myapp.userregistration')),
            ],
        ),
    ]
