# Generated by Django 5.1 on 2025-01-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='during_month',
            field=models.CharField(max_length=2),
        ),
    ]
