# Generated by Django 4.2.11 on 2024-12-19 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='amount_allotment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='amount_expended',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='balance_allotment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='countersigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='disallowed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='expenditure_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='ifa_cfa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='msme_nonmsme',
            field=models.CharField(blank=True, choices=[('msme', 'MSME'), ('non-msme', 'Non-MSME')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='received_payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='unit_id',
            field=models.CharField(help_text='Unit ID must be exactly 14 characters long.', max_length=14, validators=[django.core.validators.MinLengthValidator(14)]),
        ),
    ]
