# Generated by Django 4.2.11 on 2024-12-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userregistration_amount_allotment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='countersigned',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='received_payment',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='signature',
        ),
    ]
