# Generated by Django 4.2.11 on 2024-12-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_userregistration_countersigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('item_description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_type', models.CharField(max_length=50)),
                ('tax_type', models.CharField(max_length=50)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='myapp.userregistration')),
            ],
        ),
    ]
