# Generated by Django 5.1 on 2025-01-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userregistration_during_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='Make',
            field=models.CharField(blank=True, choices=[('MAKE IN INDIA(DPSU)', 'make in india(dpsu)'), ('MAKE IN INDIA(PSU)', 'make in india(psu)'), ('MAKE IN INDIA(STARTUP)', 'make in india(startup)'), ('MAKE IN INDIA(RAKSHA RATNAM)', 'make in india(raksha ratnam)'), ('MAKE IN INDIA(PRIVATE)', 'make in india(private)'), ('MAKE IN INDIA(DBT)', 'make in india(dbt)'), ('FOREIGN PROCUREMENT(LC)', 'foreign procurement(lc)')], max_length=30, null=True),
        ),
    ]
